name: Fix Terraform file formatting
on:
  # only run on commit and not on PRs to have "style:" commit type separete from PRs
  # pull_request: {}
  push:
    branches:
      - main
jobs:
  formatting:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: terraform fmt
        uses: dflook/terraform-fmt@90fc9225b4c109d9a6bb0b2ca0faa89490c0ba95 # v2
        with:
          path: .
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6
        with:
          commit-message: "style: automated terraform formatting"
          title: "style: automated terraform formatting"
          body: Update Terraform files to canonical format using `terraform fmt`
          branch: style/automated-terraform-fmt
          delete-branch: true
      - name: Create PR output
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"