name: Terraform docs generation
on:
  # only run on commit and not on PRs to not interfere with renovate PRs
  # contributors' PRs will get updated docs when merged to main
  # pull_request: {}
  push:
    branches:
      - main
jobs:
  docs:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Render terraform docs inside the docs/module.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@6de6da0cefcc6b4b7a5cbea4d79d97060733093c # v1.4.1
        with:
          working-dir: .
          output-file: ./docs/module.md
          output-method: inject
          output-format: markdown table
          indention: 2
          git-push: "true"
          git-commit-message: "docs: automated terraform docs update"